In [1]:
import pandas as pd
import numpy as np
import openpyxl
import seaborn as sb
import seaborn as sns
import matplotlib.pyplot as plt
import pickle
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder, OneHotEncoder, OrdinalEncoder

#for classfication
from sklearn.ensemble import RandomForestClassifier

# for resampling 
from imblearn.over_sampling import RandomOverSampler

# for checking testing results
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, classification_report, confusion_matrix

# Import Data 2

In [2]:
data=pd.read_excel("Dry_Bean_Dataset.xlsx")
data

Bean ID   Area  Perimeter  MajorAxisLength  MinorAxisLength  \
0            1  28395    610.291       208.178117       173.888747   
1            2  28734    638.018       200.524796       182.734419   
2            3  29380    624.110       212.826130       175.931143   
3            4  30008    645.884       210.557999       182.516516   
4            5  30140    620.134       201.847882       190.279279   
...        ...    ...        ...              ...              ...   
13606    13607  42097    759.696       288.721612       185.944705   
13607    13608  42101    757.499       281.576392       190.713136   
13608    13609  42139    759.321       281.539928       191.187979   
13609    13610  42147    763.779       283.382636       190.275731   
13610    13611  42159    772.237       295.142741       182.204716   

       AspectRation  Eccentricity  ConvexArea  EquivDiameter    Extent  \
0          1.197191      0.549812       28715     190.141097  0.763923   
1          1.097356      0.411785       29172     191.272750  0.783968   
2          1.209713      0.562727       29690     193.410904  0.778113   
3          1.153638      0.498616       30724     195.467062  0.782681   
4          1.060798      0.333680       30417     195.896503  0.773098   
...             ...           ...         ...            ...       ...   
13606      1.552728      0.765002       42508     231.515799  0.714574   
13607      1.476439      0.735702       42494     231.526798  0.799943   
13608      1.472582      0.734065       42569     231.631261  0.729932   
13609      1.489326      0.741055       42667     231.653248  0.705389   
13610      1.619841      0.786693       42600     231.686223  0.788962   

       Solidity  roundness  Compactness  ShapeFactor1  ShapeFactor2  \
0      0.988856   0.958027     0.913358      0.007332      0.003147   
1      0.984986   0.887034     0.953861      0.006979      0.003564   
2      0.989559   0.947849     0.908774      0.007244      0.003048   
3      0.976696   0.903936     0.928329      0.007017      0.003215   
4      0.990893   0.984877     0.970516      0.006697      0.003665   
...         ...        ...          ...           ...           ...   
13606  0.990331   0.916603     0.801865      0.006858      0.001749   
13607  0.990752   0.922015     0.822252      0.006688      0.001886   
13608  0.989899   0.918424     0.822730      0.006681      0.001888   
13609  0.987813   0.907906     0.817457      0.006724      0.001852   
13610  0.989648   0.888380     0.784997      0.007001      0.001640   

       ShapeFactor3  ShapeFactor4     Class  
0          0.834222      0.998724     SEKER  
1          0.909851      0.998430     SEKER  
2          0.825871      0.999066     SEKER  
3          0.861794      0.994199     SEKER  
4          0.941900      0.999166     SEKER  
...             ...           ...       ...  
13606      0.642988      0.998385  DERMASON  
13607      0.676099      0.998219  DERMASON  
13608      0.676884      0.996767  DERMASON  
13609      0.668237      0.995222  DERMASON  
13610      0.616221      0.998180  DERMASON  

[13611 rows x 18 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13611 entries, 0 to 13610
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Bean ID          13611 non-null  int64  
 1   Area             13611 non-null  int64  
 2   Perimeter        13611 non-null  float64
 3   MajorAxisLength  13611 non-null  float64
 4   MinorAxisLength  13611 non-null  float64
 5   AspectRation     13611 non-null  float64
 6   Eccentricity     13611 non-null  float64
 7   ConvexArea       13611 non-null  int64  
 8   EquivDiameter    13611 non-null  float64
 9   Extent           13611 non-null  float64
 10  Solidity         13611 non-null  float64
 11  roundness        13611 non-null  float64
 12  Compactness      13611 non-null  float64
 13  ShapeFactor1     13611 non-null  float64
 14  ShapeFactor2     13611 non-null  float64
 15  ShapeFactor3     13611 non-null  float64
 16  ShapeFactor4     13611 non-null  float64
 17  Class       

In [4]:
data.describe()

Bean ID           Area     Perimeter  MajorAxisLength  \
count  13611.000000   13611.000000  13611.000000     13611.000000   
mean    6806.000000   53048.284549    855.283459       320.141867   
std     3929.301592   29324.095717    214.289696        85.694186   
min        1.000000   20420.000000    524.736000       183.601165   
25%     3403.500000   36328.000000    703.523500       253.303633   
50%     6806.000000   44652.000000    794.941000       296.883367   
75%    10208.500000   61332.000000    977.213000       376.495012   
max    13611.000000  254616.000000   1985.370000       738.860153   

       MinorAxisLength  AspectRation  Eccentricity     ConvexArea  \
count     13611.000000  13611.000000  13611.000000   13611.000000   
mean        202.270714      1.583242      0.750895   53768.200206   
std          44.970091      0.246678      0.092002   29774.915817   
min         122.512653      1.024868      0.218951   20684.000000   
25%         175.848170      1.432307      0.715928   36714.500000   
50%         192.431733      1.551124      0.764441   45178.000000   
75%         217.031741      1.707109      0.810466   62294.000000   
max         460.198497      2.430306      0.911423  263261.000000   

       EquivDiameter        Extent      Solidity     roundness   Compactness  \
count   13611.000000  13611.000000  13611.000000  13611.000000  13611.000000   
mean      253.064220      0.749733      0.987143      0.873282      0.799864   
std        59.177120      0.049086      0.004660      0.059520      0.061713   
min       161.243764      0.555315      0.919246      0.489618      0.640577   
25%       215.068003      0.718634      0.985670      0.832096      0.762469   
50%       238.438026      0.759859      0.988283      0.883157      0.801277   
75%       279.446467      0.786851      0.990013      0.916869      0.834270   
max       569.374358      0.866195      0.994677      0.990685      0.987303   

       ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
count  13611.000000  13611.000000  13611.000000  13611.000000  
mean       0.006564      0.001716      0.643590      0.995063  
std        0.001128      0.000596      0.098996      0.004366  
min        0.002778      0.000564      0.410339      0.947687  
25%        0.005900      0.001154      0.581359      0.993703  
50%        0.006645      0.001694      0.642044      0.996386  
75%        0.007271      0.002170      0.696006      0.997883  
max        0.010451      0.003665      0.974767      0.999733

# prepocessing

In [5]:
#cek missing value
data.isnull().sum()

Bean ID            0
Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64

In [6]:
#menghilangkan variabel yang tidak dibutuhkan
data=data.drop(columns=['Bean ID'], inplace=False,axis=1)

In [7]:
#menghitung jumlah output
data.Class.value_counts().sort_values(ascending = False)

DERMASON    3546
SIRA        2636
SEKER       2027
HOROZ       1928
CALI        1630
BARBUNYA    1322
BOMBAY       522
Name: Class, dtype: int64

In [8]:
#melabelkan data output
data[['Class']] = data[['Class']].apply(LabelEncoder().fit_transform)

In [9]:
#menghitung jumlah output
data.Class.value_counts().sort_values(ascending = False)

3    3546
6    2636
5    2027
4    1928
2    1630
0    1322
1     522
Name: Class, dtype: int64

In [10]:
#feature selection data and split data
X = data.drop(columns='Class')
y = data.Class

In [11]:
#data traing 90% dan data testing 10% before random oversampling
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=200)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((12249, 16), (1362, 16), (12249,), (1362,))

In [12]:
#Transformasi/normalisasi data dengan MinMax before resampling
columns = ['Area','Perimeter','MajorAxisLength','MinorAxisLength','AspectRation','ConvexArea','EquivDiameter']
scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train[columns])
X_test_scale = scaler.transform(X_test[columns])

In [13]:
X_train[columns]=X_train_scale
X_test[columns]=X_test_scale

# rfc

In [14]:
seed=123
np.random.seed(seed)

In [15]:
rfc_100 = RandomForestClassifier()

# fit the model to the training set

rfc_100.fit(X_train, y_train)

# Predict on the test set results

y_pred_100 = rfc_100.predict(X_test)

In [16]:
# Check accuracy score 
print('Model accuracy score with 100 random forest : {0:0.4f}'. format(accuracy_score(y_test, y_pred_100)))

Model accuracy score with 100 random forest : 0.9163


In [17]:
cm2 = confusion_matrix(y_test, y_pred_100)

print('Confusion matrix\n\n', cm2)

Confusion matrix

 [[101   0   7   0   0   0   2]
 [  0  49   0   0   0   0   0]
 [  7   0 142   0   4   0   3]
 [  0   0   0 315   0   3  13]
 [  1   0   3   0 182   0   6]
 [  3   0   0   7   0 227   6]
 [  4   0   1  38   2   4 232]]


In [18]:
print ('accuracy_score: ',accuracy_score(y_test, y_pred_100))
print ('f1_score: ',f1_score(y_test, y_pred_100, pos_label='positive', average='micro'))
print ('recall_score: ',recall_score(y_test, y_pred_100, pos_label='positive', average='micro'))
print ('precision_score: ',precision_score(y_test, y_pred_100, pos_label='positive', average='micro'))

accuracy_score:  0.9162995594713657
f1_score:  0.9162995594713657
recall_score:  0.9162995594713657
precision_score:  0.9162995594713657


# simpan model

In [ ]:
fillname1="RFC_model.pkl"
pickle.dump(xgb1, open(fillname1,"wb"))